### ISSUE TITLE
Serializers don't work with multi-stream

### ISSUE THREAD

**Issue by yunong** [pinojs/pino-multi-stream#5]
```bash
> var pinoms = require('pino-multi-stream');
undefined
> var msLog = pinoms({serializers: pinoms.stdSerializers, streams: [{stream: process.stdout}, {stream: process.stderr}]})
undefined
> msLog.info({req: {foo: 'bar'}});
{"pid":22638,"hostname":"lgud-yunong","level":30,"time":1497550501568,"req":{"foo":"bar"},"v":1}
{"pid":22638,"hostname":"lgud-yunong","level":30,"time":1497550501570,"req":{"foo":"bar"},"v":1}
undefined
> var log = pinoms({serializers: pinoms.stdSerializers})
undefined
> log.info({req: {foo: 'bar'}});
TypeError: Cannot read property 'remoteAddress' of undefined
    at Object.asReqValue [as req] (/home/yunong/workspace/nodequark/node_modules/pino/lib/serializers.js:8:34)
    at EventEmitter.asJson (/home/yunong/workspace/nodequark/node_modules/pino/pino.js:143:77)
    at EventEmitter.pinoWrite (/home/yunong/workspace/nodequark/node_modules/pino/pino.js:201:16)
    at EventEmitter.LOG (/home/yunong/workspace/nodequark/node_modules/pino/lib/tools.js:122:10)
    at repl:1:5
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:73:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)
```

Notice here that the multistream logger is not respecting the request serializer. Is this expected or am I using the API incorrectly?

**Comment by jsumners** [comment]
Hmm, other than the `streams` option, all options should be directly passed to the actual Pino constructor -- https://github.com/pinojs/pino-multi-stream/blob/4bafea3cd6616eb35252e2be05b02cd0301b48ab/index.js#L40

It looks to me, from your error message, that this is working as intended. Pino's `asJson` method has passed the `req` property to a serializer, but the serializer is crashing because it can't find the `remoteAddress` property. I think a simply update of dependencies is going to fix this.

I have just published v2.1.1. Give that a shot and let me know if it corrects the problem.

**Comment by yunong** [comment]
@jsumners the single stream logger is working as expected by crashing, however the `msLog`, which is the multistream logger is not crashing, even tho it should, because the serializers are not run.

**Comment by jsumners** [comment]
@yunong please check https://github.com/pinojs/pino-multi-stream/blob/b459b3502ac3961934f338e439d8d943124d28eb/test/index.js#L145-L162

It looks to me like it is working correctly.

**Comment by mcollina** [comment]
I think this was solved in the last releases, feel free to reopen in case.
